import { buildSpin360FramesFromHero } from '@/lib/spin360'
import type { CatalogCategory, Product } from '@/lib/cms-types'

const SKIN = [
  'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=800&q=85',
  'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800&q=85',
  'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800&q=85',
  'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800&q=85',
  'https://images.unsplash.com/photo-1570194065650-d99fb4bedf0a?w=800&q=85',
  'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=800&q=85',
]
const HAIR = [
  'https://images.unsplash.com/photo-1527799820374-87991a7a11a1?w=800&q=85',
  'https://images.unsplash.com/photo-1591348278863-a8fb3887e2aa?w=800&q=85',
  'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=85',
]
const MKP = [
  'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=800&q=85',
  'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=85',
  'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=800&q=85',
  'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?w=800&q=85',
]
const FRAG = [
  'https://images.unsplash.com/photo-1541643600914-78b084683702?w=800&q=85',
  'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&q=85',
]
const BRUSH = [
  'https://images.unsplash.com/photo-1607006483224-46ab71bbeabc?w=800&q=85',
  'https://images.unsplash.com/photo-1583241475880-083f84372725?w=800&q=85',
]

export const SEED_CATALOG_CATEGORIES: CatalogCategory[] = [
  { label: 'Skincare', slug: 'skincare', desc: 'Serums, moisturisers, SPF and treatments for every skin type.', img: SKIN[0] },
  { label: 'Haircare', slug: 'haircare', desc: 'Bond-repair, scalp care, and growth treatments for all hair types.', img: HAIR[0] },
  { label: 'Make-Up', slug: 'makeup', desc: 'Foundation, lips, eyes and complexion — prestige makeup for every look.', img: MKP[0] },
  { label: 'Brushes', slug: 'brushes', desc: 'Professional-grade tools engineered for flawless application.', img: BRUSH[0] },
  { label: 'Fragrance', slug: 'fragrance', desc: 'Perfumes and eau de toilette crafted by master perfumers.', img: FRAG[0] },
  { label: 'Body Care', slug: 'bodycare', desc: 'Body oils, scrubs, and lotions for luminous, nourished skin.', img: SKIN[4] },
]

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'sk-001', slug: 'lumiere-vitamin-c-serum',
    name: 'Vitamin C Radiance Serum', brand: 'Lumière Paris',
    category: 'Skincare', categorySlug: 'skincare',
    price: 89, originalPrice: 110, rating: 4.8, reviews: 342,
    badge: 'Best Seller',
    description: 'A potent 20% Vitamin C serum that visibly brightens, firms, and protects skin against environmental aggressors.',
    longDescription: 'Formulated with stabilised L-Ascorbic Acid at 20% concentration, this professional-grade serum delivers visible results in 7 days. Fortified with Vitamin E and Ferulic Acid for maximum antioxidant protection and stability.',
    benefits: ['Visibly brighter skin in 7 days', 'Reduces dark spots & hyperpigmentation', 'Boosts collagen production', 'Protects against free radical damage'],
    howToUse: 'Apply 3-4 drops to clean, dry skin each morning. Follow with SPF. For best results, use before moisturiser.',
    ingredients: 'L-Ascorbic Acid 20%, Vitamin E, Ferulic Acid, Hyaluronic Acid, Niacinamide',
    img: SKIN[0], imgs: SKIN.slice(0, 3), spin360: buildSpin360FramesFromHero(SKIN[0]),
    variants: [{ label: '30ml', value: '30ml' }, { label: '50ml', value: '50ml' }],
    inStock: true, featured: true,
  },
  {
    id: 'sk-002', slug: 'aurore-retinol-night-cream',
    name: 'Retinol Renewal Night Cream', brand: 'Aurore Skincare',
    category: 'Skincare', categorySlug: 'skincare',
    price: 124, rating: 4.7, reviews: 218,
    badge: 'New',
    description: 'A luxurious encapsulated retinol cream that resurfaces and renews skin overnight without irritation.',
    longDescription: 'Our patented encapsulated retinol technology releases active ingredients gradually through the night, delivering the anti-ageing benefits of retinol without the sensitivity. Wake up to visibly smoother, plumper skin.',
    benefits: ['Reduces fine lines overnight', 'Improves skin texture', 'Zero irritation formula', 'Clinical-strength results'],
    howToUse: 'Apply a pea-sized amount to face and neck every evening after cleansing. Always use SPF the following morning.',
    ingredients: 'Encapsulated Retinol 0.3%, Peptide Complex, Shea Butter, Ceramides, Squalane',
    img: SKIN[1], imgs: [SKIN[1], SKIN[2], SKIN[3]], spin360: buildSpin360FramesFromHero(SKIN[1]),
    variants: [{ label: '50ml', value: '50ml' }],
    inStock: true, featured: true,
  },
  {
    id: 'sk-003', slug: 'velours-hyaluronic-moisture',
    name: 'Plumping Hyaluronic Moisturiser', brand: 'Velours Beauty',
    category: 'Skincare', categorySlug: 'skincare',
    price: 68, rating: 4.9, reviews: 512,
    badge: 'Fan Favourite',
    description: 'Triple-weight hyaluronic acid that plumps and hydrates for up to 72 hours.',
    longDescription: 'Three molecular weights of hyaluronic acid penetrate every layer of skin, delivering instant and long-lasting hydration. Fragrance-free and suitable for all skin types including sensitive.',
    benefits: ['72-hour hydration', 'Plumps fine lines instantly', 'Fragrance-free formula', 'Suitable for all skin types'],
    howToUse: 'Apply morning and evening to clean skin. Layer under serums and moisturisers or use alone as a lightweight hydrator.',
    ingredients: 'Sodium Hyaluronate (3 molecular weights), Glycerin, Niacinamide, Centella Asiatica',
    img: SKIN[2], imgs: [SKIN[2], SKIN[4], SKIN[5]], spin360: buildSpin360FramesFromHero(SKIN[2]),
    variants: [{ label: '30ml', value: '30ml' }, { label: '50ml', value: '50ml' }, { label: '100ml', value: '100ml' }],
    inStock: true,
  },
  {
    id: 'sk-004', slug: 'soleil-spf50-serum',
    name: 'Invisible UV Shield SPF 50+', brand: 'Soleil Cosmetics',
    category: 'Skincare', categorySlug: 'skincare',
    price: 52, rating: 4.6, reviews: 189,
    description: 'Lightweight, invisible SPF 50+ that doubles as a skincare primer.',
    longDescription: 'Reef-safe mineral and chemical hybrid formula that sits invisibly on all skin tones. Enriched with antioxidants and skin-brightening niacinamide.',
    benefits: ['SPF 50+ broad spectrum', 'No white cast', 'Reef-safe formula', 'Primer finish'],
    howToUse: 'Apply generously as the final step of your morning routine. Reapply every 2 hours in direct sun.',
    ingredients: 'Zinc Oxide, Octinoxate, Niacinamide, Vitamin C, Glycerin',
    img: SKIN[3], imgs: [SKIN[3], SKIN[0], SKIN[1]], spin360: buildSpin360FramesFromHero(SKIN[3]),
    variants: [{ label: '50ml', value: '50ml' }],
    inStock: true,
  },
  {
    id: 'hc-001', slug: 'noir-repair-shampoo',
    name: 'Repair & Restore Shampoo', brand: 'Noir Atelier',
    category: 'Haircare', categorySlug: 'haircare',
    price: 44, rating: 4.7, reviews: 276,
    badge: 'Best Seller',
    description: 'Bond-repair shampoo that rebuilds damaged hair from within with every wash.',
    longDescription: 'Powered by our BondFix technology, this luxurious shampoo rebuilds broken disulphide bonds caused by heat, colour, and chemical treatments — restoring strength, shine, and elasticity from the first wash.',
    benefits: ['Repairs broken bonds', 'Restores shine & elasticity', 'Safe for colour-treated hair', 'Sulphate-free'],
    howToUse: 'Massage into wet hair and scalp. Leave for 2 minutes before rinsing. Follow with Repair Conditioner.',
    ingredients: 'BondFix Complex, Keratin, Panthenol, Argan Oil, Biotin',
    img: HAIR[0], imgs: HAIR, spin360: buildSpin360FramesFromHero(HAIR[0]),
    variants: [{ label: '250ml', value: '250ml' }, { label: '500ml', value: '500ml' }],
    inStock: true, featured: true,
  },
  {
    id: 'hc-002', slug: 'botanik-scalp-serum',
    name: 'Scalp Revive Growth Serum', brand: 'Botanik Lab',
    category: 'Haircare', categorySlug: 'haircare',
    price: 78, rating: 4.5, reviews: 134,
    badge: 'New',
    description: 'Clinical-strength scalp serum that stimulates growth and reduces shedding in 8 weeks.',
    longDescription: 'Combining Redensyl, Anagain, and Caffeine, our triple-action growth serum targets dormant follicles and extends the hair growth cycle. Clinically proven to reduce shedding by 47% in 8 weeks.',
    benefits: ['47% reduction in hair loss', 'Stimulates new growth', 'Suitable for all hair types', 'No residue formula'],
    howToUse: 'Apply 1ml directly to scalp sections using the precision applicator. Massage in gently. Use daily for best results.',
    ingredients: 'Redensyl 3%, Anagain 4%, Caffeine 1%, Biotin, Zinc PCA',
    img: HAIR[1], imgs: [HAIR[1], HAIR[2], HAIR[0]], spin360: buildSpin360FramesFromHero(HAIR[1]),
    variants: [{ label: '60ml', value: '60ml' }],
    inStock: true,
  },
  {
    id: 'mk-001', slug: 'maison-velvet-foundation',
    name: 'Velvet Skin Tint Foundation', brand: 'Maison Éclat',
    category: 'Make-Up', categorySlug: 'makeup',
    price: 62, rating: 4.8, reviews: 428,
    badge: 'Award Winner',
    description: 'Buildable medium-coverage foundation with a natural velvet finish that lasts 24 hours.',
    longDescription: 'Our most-loved foundation reformulated with skincare actives. Buildable from sheer to medium coverage with a breathable, velvet finish that photographs beautifully. 40 inclusive shades.',
    benefits: ['24-hour wear', 'Buildable coverage', '40 inclusive shades', 'SPF 20 protection'],
    howToUse: 'Apply with fingertips, brush, or sponge for different coverage levels. Set with powder for extended wear.',
    ingredients: 'Aqua, Cyclopentasiloxane, Titanium Dioxide, Niacinamide, Hyaluronic Acid',
    img: MKP[0], imgs: MKP.slice(0, 3), spin360: buildSpin360FramesFromHero(MKP[0]),
    variants: [{ label: 'Ivory 01', value: 'ivory-01' }, { label: 'Sand 12', value: 'sand-12' }, { label: 'Warm 24', value: 'warm-24' }, { label: 'Deep 36', value: 'deep-36' }],
    inStock: true, featured: true,
  },
  {
    id: 'mk-002', slug: 'lumiere-lip-plumper',
    name: 'Plump & Shine Lip Gloss', brand: 'Lumière Paris',
    category: 'Make-Up', categorySlug: 'makeup',
    price: 38, rating: 4.6, reviews: 312,
    description: 'High-shine lip gloss with hyaluronic acid for an instant plumping effect.',
    longDescription: 'Infused with Volulip peptide and Hyaluronic Acid, this non-sticky gloss delivers immediate volume and long-term plumping with continued use. Available in 12 universally flattering shades.',
    benefits: ['Instant plumping effect', 'Non-sticky formula', '12 universal shades', 'Long-term volume with use'],
    howToUse: 'Apply to bare lips or over lipstick. Focus on the centre of the lips for maximum plumping effect.',
    ingredients: 'Volulip Peptide, Hyaluronic Acid, Vitamin E, Peppermint Oil',
    img: MKP[1], imgs: [MKP[1], MKP[2], MKP[3]], spin360: buildSpin360FramesFromHero(MKP[1]),
    variants: [{ label: 'Nude Glow', value: 'nude' }, { label: 'Rose Pink', value: 'rose' }, { label: 'Berry', value: 'berry' }],
    inStock: true,
  },
  {
    id: 'br-001', slug: 'maison-foundation-brush',
    name: 'Precision Foundation Brush', brand: 'Maison Éclat',
    category: 'Brushes', categorySlug: 'brushes',
    price: 56, rating: 4.9, reviews: 198,
    badge: 'Best Seller',
    description: 'Dense, flat-top synthetic brush engineered for flawless foundation application.',
    longDescription: 'Hand-crafted with ultra-soft vegan bristles that are 30% denser than industry standard, this brush delivers streak-free, airbrushed coverage. The ergonomic weighted handle provides professional-level control.',
    benefits: ['Vegan synthetic bristles', 'Streak-free coverage', 'Ergonomic weighted handle', 'Easy to clean'],
    howToUse: 'Pump product onto brush or back of hand. Apply using small circular buffing motions, working outward from the centre of the face.',
    ingredients: 'Vegan synthetic fibre, Rose-gold aluminium ferrule, Lacquered birch wood handle',
    img: BRUSH[0], imgs: BRUSH, spin360: buildSpin360FramesFromHero(BRUSH[0]),
    variants: [{ label: 'Single', value: 'single' }, { label: 'Set of 5', value: 'set-5' }],
    inStock: true, featured: true,
  },
  {
    id: 'br-002', slug: 'velours-kabuki-brush',
    name: 'Pro Kabuki Powder Brush', brand: 'Velours Beauty',
    category: 'Brushes', categorySlug: 'brushes',
    price: 42, rating: 4.7, reviews: 145,
    description: 'Fluffy dome-shaped brush for seamless powder and blush application.',
    longDescription: 'Professional-grade kabuki brush with ultra-soft taklon fibres that pick up and deposit powder products evenly. Perfect for setting powder, bronzer, or blush.',
    benefits: ['Ultra-soft taklon fibres', 'Seamless powder blending', 'Multi-use: powder, blush, bronzer', 'Cruelty-free'],
    howToUse: 'Swirl into powder product, tap off excess. Apply to face using circular or sweeping motions.',
    ingredients: 'Taklon synthetic fibre, Aluminium ferrule, Bamboo handle',
    img: BRUSH[1], imgs: [BRUSH[1], BRUSH[0]], spin360: buildSpin360FramesFromHero(BRUSH[1]),
    variants: [{ label: 'Natural', value: 'natural' }],
    inStock: true,
  },
  {
    id: 'fr-001', slug: 'noir-midnight-edp',
    name: 'Midnight Oud Eau de Parfum', brand: 'Noir Atelier',
    category: 'Fragrance', categorySlug: 'fragrance',
    price: 185, rating: 4.9, reviews: 89,
    badge: 'Limited Edition',
    description: 'A hypnotic oriental fragrance of oud, black rose, and warm amber.',
    longDescription: 'An opulent evening fragrance that opens with Damascus Rose and Black Pepper before settling into a rich heart of aged Oud Wood. The dry-down reveals warm Amber and White Musk for a captivating sillage that lasts well into the night.',
    benefits: ['12+ hour longevity', '30% concentration (Parfum)', 'Hand-blown glass bottle', 'Refillable design'],
    howToUse: 'Spray onto pulse points — wrists, neck, décolletage — from 15cm distance. Layer with our matching body lotion for extended longevity.',
    ingredients: 'Top: Black Pepper, Bergamot. Heart: Damascus Rose, Oud Wood. Base: Amber, White Musk, Sandalwood',
    img: FRAG[0], imgs: FRAG, spin360: buildSpin360FramesFromHero(FRAG[0]),
    variants: [{ label: '50ml', value: '50ml' }, { label: '100ml', value: '100ml' }],
    inStock: true, featured: true,
  },
  {
    id: 'fr-002', slug: 'soleil-bloom-edt',
    name: 'Bloom Floral Eau de Toilette', brand: 'Soleil Cosmetics',
    category: 'Fragrance', categorySlug: 'fragrance',
    price: 98, rating: 4.6, reviews: 156,
    description: 'A fresh, radiant floral bouquet with notes of peony, jasmine, and white cedar.',
    longDescription: 'A light, sophisticated floral for everyday wear. The opening burst of Peony and Lychee transitions beautifully into a romantic Jasmine and Rose heart before settling on a clean Cedar and Musk base.',
    benefits: ['6-8 hour wear', 'Light, versatile fragrance', 'Suitable for all seasons', 'Vegan formula'],
    howToUse: 'Apply to pulse points. Layer with our matching shower gel for longer-lasting fragrance.',
    ingredients: 'Top: Peony, Lychee. Heart: Jasmine, Rose. Base: White Cedar, Musk',
    img: FRAG[1], imgs: [FRAG[1], FRAG[0]], spin360: buildSpin360FramesFromHero(FRAG[1]),
    variants: [{ label: '30ml', value: '30ml' }, { label: '75ml', value: '75ml' }],
    inStock: true,
  },
  {
    id: 'bc-001', slug: 'lumiere-body-oil',
    name: 'Golden Glow Dry Body Oil', brand: 'Lumière Paris',
    category: 'Body Care', categorySlug: 'bodycare',
    price: 72, rating: 4.8, reviews: 203,
    badge: 'New',
    description: 'A fast-absorbing dry body oil that leaves skin luminous, satin-soft, and lightly scented.',
    longDescription: 'Infused with 24-karat gold flecks and a blend of Marula, Argan, and Rosehip oils, this luxurious dry oil absorbs in seconds, leaving skin with a satin sheen and a delicate floral fragrance.',
    benefits: ['Absorbs in 60 seconds', '24k gold luminosity', 'Nourishes for 24 hours', 'Vegan & cruelty-free'],
    howToUse: 'Spray generously onto skin after showering. Massage in gently or leave to absorb. Can be used on face, body, and hair.',
    ingredients: 'Marula Oil, Argan Oil, Rosehip Oil, Vitamin E, 24K Gold Flecks',
    img: SKIN[4], imgs: [SKIN[4], SKIN[5], SKIN[0]], spin360: buildSpin360FramesFromHero(SKIN[4]),
    variants: [{ label: '100ml', value: '100ml' }, { label: '200ml', value: '200ml' }],
    inStock: true,
  },
]
